Completed fp2 excersice
yuriibaraniuk/study pull request #3
Opened 2021-11-20 20:18 UTC by yuriibaraniuk

2021-11-22 12:25 UTC, Andrew8xx8 requested changes

2021-11-22 12:25 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +      def my_each(&blk)
`blk` не читаемое название, не стоит использовать сокращения для экономии одной буквы, нормально назвать `block`

Исправить нужно здесь и ниже

2021-11-22 12:25 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        first_element = first
Для разделения на голову и хвост, нужно использовать `*`, а не вычислять длинну.

2021-11-25 19:29 UTC, yuriibaraniuk commented on test/exercise/fp2/solution.rb
> +      def my_each(&blk)
Исправил

2021-11-25 19:30 UTC, yuriibaraniuk commented on test/exercise/fp2/solution.rb
> +        first_element = first
Исправил на использование `*`

2021-11-29 10:57 UTC, merged